# A trigger service using unsigned integers

int32 data      # data being sent through the call
---
bool success    # indicate successful run of triggered service
string message  # informational, e.g. for error messages